### PR TITLE
Fix transpose doc

### LINKED ISSUE #6958: The matrix in the doc of transpose_op display wrong format
The docs display wrong format matrix after being builded by `SPHINX`.
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/transpose_op.cc#L84

### PR DESCRIPTION
**Pull request by wanghaoshuang**
fix #6958

### CODE REVIEW

File: paddle/operators/transpose_op.cc [hunk 1]
```diff
@@ -72,17 +72,29 @@ Transpose Operator.
...
-given axis is: [1, 0]
-
-output = input.transpose(axis)
-then the output is:
-array([[0, 3],
-       [1, 4],
-       [2, 5]])
+For example:
+
+    .. code-block:: python
```
Comment (pkuyym) [inline paddle/operators/transpose_op.cc]: `python` or `text`，please try to compare the preview

Comment (wanghaoshuang) [reply paddle/operators/transpose_op.cc]: Thx. `text` is more fitting here.
