### PR TITLE
fix some warning

### LINKED ISSUE #7072: some warning of for_range.h and MKLDNNLRNLayer.cpp
```
[06:34:16]W:	 [Step 1/1] /paddle/paddle/platform/for_range.h:66:28: warning: comparison between signed and unsigned integer 

expressions [-Wsign-compare]
[06:34:16]W:	 [Step 1/1]      int block_size = limit_ <= num_threads ? limit_ : num_threads;
[06:34:16]W:	 [Step 1/1]                             ^
[06:34:16]W:	 [Step 1/1] /paddle/paddle/platform/for_range.h: In instantiation of 'void 

paddle::platform::ForRange<paddle::platform::CUDADeviceContext>::operator()(Function) const [with Function = 

paddle::operators::AdamFunctor<float>]':
[06:34:16]W:	 [Step 1/1] /paddle/paddle/operators/adam_op.h:122:10:   required from 'void 

paddle::operators::AdamOpKernel<DeviceContext, T>::Compute(const paddle::framework::ExecutionContext&) const [with DeviceContext = 

paddle::platform::CUDADeviceContext; T = float]'
[06:34:16]W:	 [Step 1/1] /tmp/tmpxft_00005965_00000000-4_adam_op.compute_61.cudafe1.stub.c:34:27:   required from here
[06:34:16]W:	 [Step 1/1] /paddle/paddle/platform/for_range.h:66:28: warning: comparison between signed and unsigned integer 

expressions [-Wsign-compare]
```
```
[06:38:51]W:	 [Step 1/1] In file included from 

/paddle/build/third_party/install/protobuf/include/google/protobuf/stubs/common.h:40:0,
[06:38:51]W:	 [Step 1/1]                  from /paddle/build/proto/ModelConfig.pb.h:9,
[06:38:51]W:	 [Step 1/1]                  from /paddle/paddle/gserver/layers/Layer.h:19,
[06:38:51]W:	 [Step 1/1]                  from /paddle/paddle/gserver/layers/MKLDNNLayer.h:18,
[06:38:51]W:	 [Step 1/1]                  from /paddle/paddle/gserver/layers/MKLDNNLRNLayer.h:17,
[06:38:51]W:	 [Step 1/1]                  from /paddle/paddle/gserver/layers/MKLDNNLRNLayer.cpp:15:
[06:38:51]W:	 [Step 1/1] /paddle/build/third_party/install/glog/include/glog/logging.h: In instantiation of 'std::__cxx11::string* 

google::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = int; T2 = long unsigned int; std::__cxx11::string = 

std::__cxx11::basic_string<char>]':
[06:38:51]W:	 [Step 1/1] /paddle/paddle/gserver/layers/MKLDNNLRNLayer.cpp:32:3:   required from here
[06:38:51]W:	 [Step 1/1] /paddle/build/third_party/install/glog/include/glog/logging.h:717:32: warning: comparison between signed 

and unsigned integer expressions [-Wsign-compare]
[06:38:51]W:	 [Step 1/1]  DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
[06:38:51]W:	 [Step 1/1]                                 ^
[06:38:51]W:	 [Step 1/1] /paddle/build/third_party/install/protobuf/include/google/protobuf/stubs/port.h:200:53: note: in 

definition of macro 'GOOGLE_PREDICT_TRUE'
[06:38:51]W:	 [Step 1/1]  #define GOOGLE_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
[06:38:51]W:	 [Step 1/1]                                                      ^
[06:38:51]W:	 [Step 1/1] /paddle/build/third_party/install/glog/include/glog/logging.h:717:1: note: in expansion of macro 

'DEFINE_CHECK_OP_IMPL'
[06:38:51]W:	 [Step 1/1]  DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
```

### PR DESCRIPTION
**Pull request by luotao1**
fix #7072

### CODE REVIEW

File: paddle/gserver/layers/MKLDNNLRNLayer.cpp [hunk 1]
```diff
@@ -29,7 +29,7 @@ bool MKLDNNLRNLayer::init(const LayerMap& layerMap,
   }
 
   /* the size of inputs for norm-layer is 1 */
-  CHECK_EQ(config_.inputs_size(), 1);
+  CHECK_EQ(config_.inputs_size(), 1UL);
```
Comment (reyoung) [inline paddle/gserver/layers/MKLDNNLRNLayer.cpp]: That will make compile error on some gcc version.

config_.inputs_size() is a integer, not a size_t.

Comment (luotao1) [reply paddle/gserver/layers/MKLDNNLRNLayer.cpp]: Thanks for @reyoung, but why there is a warning here?
