### PR TITLE
Fix macos compile

### LINKED ISSUE #2588: problem of inconsistent-missing-override
I build the newest develop branch of Paddle on my macbook and get the error below:
May be it's because I update my osx system last day. But I think this problem should be resolved.

```shell
/Users/qiaolongfei/project/paddle-test/paddle/gserver/gradientmachines/NeuralNetwork.cpp:312:16: error: 'start' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  virtual void start() {
               ^
/Users/qiaolongfei/project/paddle-test/paddle/gserver/evaluators/Evaluator.h:55:16: note: overridden virtual function is here
  virtual void start() {
               ^
/Users/qiaolongfei/project/paddle-test/paddle/gserver/gradientmachines/NeuralNetwork.cpp:318:16: error: 'finish' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  virtual void finish() {
```

### PR DESCRIPTION
**Pull request by reyoung**
Please use `override` not `virtual` in sub-classes.
`override` can check if there is a method in `parent` while compiling.

Fix #2588

### CODE REVIEW

**Comment by jacquesqiao** [comment]
Thanks @reyoung tell me that In subclass we should write only virtual or only override, if we use both, clang will throw error like "error: 'xxx' overrides a member function but is not marked 'override'"

LGTM!

File: paddle/gserver/gradientmachines/NeuralNetwork.cpp [hunk 1]
```diff
@@ -309,35 +309,35 @@ class CombinedEvaluator : public Evaluator {
   void addEvaluator(std::unique_ptr<Evaluator>&& evaluator) {
     evaluators_.emplace_back(std::move(evaluator));
   }
-  virtual void start() {
+  void start() override {
```
Comment (wangkuiyi) [inline paddle/gserver/gradientmachines/NeuralNetwork.cpp]: I don't get it -- why is keyword `override` a key to Mac OS X build? @reyoung @jacquesqiao

Comment (wangkuiyi) [inline paddle/gserver/gradientmachines/NeuralNetwork.cpp]: OK. I got it from @jacquesqiao 's [comment](https://github.com/PaddlePaddle/Paddle/pull/2591#issuecomment-310841709).
