### PR TITLE
Fix send_recv unit test

### LINKED ISSUE #8559: SendRecv unit test should be fixed
Build failed on CI: https://paddleci.ngrok.io/viewLog.html?buildId=28964&buildTypeId=Paddle_DistributedUnitTestNightly&tab=buildResultsDiv

```bash
/paddle/paddle/fluid/operators/send_recv_op_test.cc: In function ‘void AddOp(const string&, const VariableNameMap&, const VariableNameMap&, paddle::framework::AttributeMap, paddle::framework::BlockDesc*)’:
/paddle/paddle/fluid/operators/send_recv_op_test.cc:98:34: error: ‘paddle::framework::proto::DataType’ has not been declared
       var->SetDataType(f::proto::DataType::FP32);
                                  ^
paddle/fluid/operators/CMakeFiles/test_send_recv.dir/build.make:62: recipe for target 'paddle/fluid/operators/CMakeFiles/test_send_recv.dir/send_recv_op_test.cc.o' failed
```

### PR DESCRIPTION
**Pull request by Yancey1989**
Fixed #8559

### CODE REVIEW

File: paddle/fluid/operators/listen_and_serv_op.cc [hunk 1]
```diff
@@ -129,6 +129,8 @@ class ListenAndServOp : public framework::OperatorBase {
       }
       if (exit_flag) {
         rpc_service_->ShutDown();
+        rpc_service_->SetCond(1);
```
Comment (typhoonzero) [inline paddle/fluid/operators/listen_and_serv_op.cc]: Why need this condition?

Comment (Yancey1989) [reply paddle/fluid/operators/listen_and_serv_op.cc]: If not, send op wouldn't exit, it will hang on `Get` operation.
