### PR TITLE
Fix cpplint format check

### LINKED ISSUE #10337: cpplint error in `hl_base.h`
The latest commit can't be compiled successfully, the error is:
```
include/hl_base.h:248:  #endif line should be "#endif  // HL_BASE_H_"  [build/header_guard] [5]
```

### PR DESCRIPTION
**Pull request by JiayiFeng**
fixes #10337

### CODE REVIEW

File: paddle/cuda/include/hl_base.h [hunk 1]
```diff
@@ -207,8 +206,8 @@ typedef struct {
 
 #ifdef __NVCC__
 
-#include "cuda_runtime.h"
-#include "hl_cuda.h"
+#include "./cuda_runtime.h"
```
Comment (pkuyym) [inline paddle/cuda/include/hl_base.h]: May change to `#include <cuda_runtime.h>` ?

File: paddle/cuda/include/hl_base.h [hunk 2]
```diff
@@ -207,8 +206,8 @@ typedef struct {
...
+#include "./hl_cuda.h"
```
Comment (pkuyym) [inline paddle/cuda/include/hl_base.h]: `#include "paddle/cuda/include/hl_cuda.h"` is better? Please double check.
