### PR TITLE
Enforce rpc timeout

### LINKED ISSUE #11880: train因Deadline Exceeded连不上ps会core dump，程序应该平稳退出
End pass 4, train_loss 2.88446474075, train_acc1 0.378594011068, train_acc5 0.633796095848, test_loss 2.4196540374, test_acc1 0.44827724359, test_acc5 0.70953525641
F0628 11:17:58.649018   220 grpc_client.cc:248] var: name:[batch_norm_22.w_0] ep:[192.168.16.34:5002] grpc error:Deadline Exceeded
*** Check failure stack trace: ***
    @     0x7f1a1031d07d  google::LogMessage::Fail()
    @     0x7f1a10320b2c  google::LogMessage::SendToLog()
    @     0x7f1a1031cba3  google::LogMessage::Flush()
    @     0x7f1a1032203e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1a100d0db0  paddle::operators::distributed::GRPCClient::Proceed()
    @     0x7f1a21fafc80  (unknown)
    @     0x7f1a6312f6ba  start_thread
    @     0x7f1a62e6541d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
程序应该平稳退出

### PR DESCRIPTION
**Pull request by Yancey0623**
fixed #11880

### CODE REVIEW

File: paddle/fluid/operators/checkpoint_notify_op.cc [hunk 1]
```diff
@@ -48,7 +48,7 @@ class CheckpointNotifyOp : public framework::OperatorBase {
       VLOG(3) << "checkpoint notify sending lookup table: " << lookup_table_name
               << " and dir:" << dir << " to " << epmap[i];
     }
-    rpc_client->Wait();
+    PADDLE_ENFORCE(rpc_client->Wait(), "internal error in RPCClient");
```
Comment (typhoonzero) [inline paddle/fluid/operators/checkpoint_notify_op.cc:51]: This will throw an exception and exit, is this expected?

Comment (gongweibao) [reply paddle/fluid/operators/checkpoint_notify_op.cc:51]: 应该可以。如果Job需要容错，可以走容错模式。

Comment (Yancey0623) [reply paddle/fluid/operators/checkpoint_notify_op.cc:51]: Yes, the RPC error would lead to the uncertain result, I think we need to exit and for the fault-tolerant training in future, we can restart the failed node and continue the training.

**Review by typhoonzero — APPROVED** [review]
