### PR TITLE
refine inference_lib_dist after code move, and add it to docker/build.sh

### LINKED ISSUE #8378: Add `make inference_lib_dist` to teamcity
After #8344 and #8363, the code structure is changed, thus, `make inference_lib_dist` runs wrong. We should add this command in [docker/build.sh](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh) to ensure this command correctly.

### PR DESCRIPTION
**Pull request by luotao1**
fix #8378 and https://github.com/PaddlePaddle/Paddle/pull/7977#pullrequestreview-94668927

### CODE REVIEW

File: paddle/scripts/docker/build.sh [hunk 1]
```diff
@@ -204,6 +204,17 @@ function gen_capi_package() {
   fi
 }
 
+function gen_fluid_inference_lib() {
+    if [ ${WITH_C_API:-OFF} == "OFF" ] ; then
+    cat <<EOF
+    ========================================
+    Building fluid inference library ...
```
Comment (Xreki) [inline paddle/scripts/docker/build.sh]: `inference_lib`在`run_build`后已经build出来了，这里应该是部署，而不是构建。可以在下一个PR里面修一下。
