### PR TITLE
Fix REGISTER_OP_WITHOUT_GRADIENT

### LINKED ISSUE #18794: gaussian_random 没有GradOpMaker无法反向
版本paddle 1.5 CUDA 97 

复现代码：https://github.com/YingjingLu/Paddle-Issues/blob/master/Issue2.py
去掉gaussian_normal可以正确反向
```
  File ".\Issue2.py", line 420, in <module>
    _, grad_list = optim.minimize( loss )
  File "C:\Users\StevenLu\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\optimizer.py", line 498, in minimize
    no_grad_set=no_grad_set)
  File "C:\Users\StevenLu\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\optimizer.py", line 403, in backward
    no_grad_set, callbacks)
  File "C:\Users\StevenLu\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\backward.py", line 511, in append_backward
    grad_to_var, callbacks)
  File "C:\Users\StevenLu\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\backward.py", line 297, in _append_backward_ops_
    op.desc, cpt.to_text(no_grad_dict[block.idx]), grad_sub_block_list)
paddle.fluid.core.EnforceNotMet: grad_op_maker_ should not be null
Operator GradOpMaker has not been registered. at [D:\1.4.1\paddle\paddle/fluid/framework/op_info.h:64]
```

### PR DESCRIPTION
**Pull request by chengduoZH**
Fix https://github.com/PaddlePaddle/Paddle/issues/18794

### CODE REVIEW

File: paddle/fluid/framework/op_registry.h [hunk 1]
```diff
@@ -53,8 +54,9 @@ class Registrar {
 template <typename... ARGS>
 struct OperatorRegistrar : public Registrar {
   explicit OperatorRegistrar(const char* op_type) {
-    PADDLE_ENFORCE(!OpInfoMap::Instance().Has(op_type),
-                   "'%s' is registered more than once.", op_type);
+    if (OpInfoMap::Instance().Has(op_type)) {
+      PADDLE_THROW("'%s' is registered more than once.", op_type);
+    }
```
Comment (chengduoZH) [inline paddle/fluid/framework/op_registry.h:59]: The changes here are a bit disgusting, but I have no other way to comply with the "No PADDLE_ENROCE" rule.

Comment (chenwhql) [reply paddle/fluid/framework/op_registry.h:59]: according the new rule:
```
// 判断是否true
PADDLE_ENFORCE(ctx->HasInput("X")); // 修改前
PADDLE_ENFORCE_EQ(ctx->HasInput("X"), true); //修改后
```
here can be 
```
PADDLE_ENFORCE_EQ(OpInfoMap::Instance().Has(op_type), false, "'%s' is registered more than once.", op_type);
```
although I think this isn't very good.

**Review by chenwhql — APPROVED** [review]
