### PR TITLE
not use transferscope cache in cpu case

### LINKED ISSUE #15032: test_analyzer_* random crashs at `compare_mkldnn`
- test_analyzer_small_dam random crashes at `compare_mkldnn` in three nightly CI at a same machine (5117).
```
test_analyzer_small_dam (NUMERICAL)
```
http://ci.paddlepaddle.org/viewLog.html?buildId=40622&tab=buildLog&buildTypeId=Paddle_PrCiNight&logTab=tree&filter=all&_focus=21635
http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&buildTypeId=Paddle_PrCiNight&buildId=40460&_focus=22113
http://ci.paddlepaddle.org/viewLog.html?buildId=40324&tab=buildLog&buildTypeId=Paddle_PrCiNight&logTab=tree&filter=all&_focus=21764
-  test_analyzer_dam random crashes at `compare_mkldnn` in nightly CI
http://ci.paddlepaddle.org/viewLog.html?buildId=44600&tab=buildLog&buildTypeId=Paddle_PrCiNight&logTab=tree&filter=all&_focus=22935
- test_analyzer_mobilenet_depthwise_conv crashes at `compare_mkldnn` in nightly CI
http://ci.paddlepaddle.org/viewLog.html?buildId=44596&tab=buildLog&buildTypeId=Paddle_PrCiNight&logTab=tree&filter=all&_focus=23004

### PR DESCRIPTION
**Pull request by LeoZhao-BJ**
For naiveexecutor on CPU model, do not use transferscope cache, and release new created transferscope at the end of op RunImpl() to avoid memory leak.

This PR is also trying to fix https://github.com/PaddlePaddle/Paddle/issues/15032#issuecomment-509959284

### CODE REVIEW

**Comment by LeoZhao-BJ** [comment]
with PR#18372 sample = 1000, detect model

before change:
performance:  sample latency: 30.4646ms, fps: 32.8249, data type: float ======
memory: max virt 3.3GB, max res: 1.1GB

after change:
performance: sample latency: 30.5578ms, fps: 32.7249, data type: float ======
memory:  max virt 3.3GB, max res: 1.1GB

File: paddle/fluid/framework/operator.cc [hunk 1]
```diff
@@ -981,6 +981,12 @@ void OperatorWithKernel::RunImpl(const Scope& scope,
       }
     }
   }
+
+  if (transfer_scope && !run_by_executor_ &&
+      (platform::is_cpu_place(kernel_type_->place_))) {
+    std::cout << "delete scope transfer_scope=" << transfer_scope << "\n";
```
Comment (luotao1) [inline paddle/fluid/framework/operator.cc]: If a GPU model with this Op runs on CPU, will it fail?

Comment (LeoZhao-BJ) [reply paddle/fluid/framework/operator.cc]: I think transferscope cache is only for the case that doing convert from cpu tensor to gpu tensor with gpu kernel, in this case, framework will allocate output tensor inside of gpu, then trigger gpu memory explosion issue.
so maybe checking kernel_type_->place_ is enough, even for TryCreateTransferScope part.

Comment (luotao1) [reply paddle/fluid/framework/operator.cc]: > I think transferscope cache is only for the case that doing convert from cpu tensor to gpu tensor with gpu kernel

We have the case "a GPU model with this Op runs on CPU", please see #16981 and #17048

**Comment by luotao1** [comment]
I run a CE inference Job first: http://ce.paddlepaddle.org:8080/viewLog.html?tab=buildLog&buildTypeId=Inference_Build&buildId=52506 which may have the case "a GPU model with this Op runs on CPU"

File: paddle/fluid/framework/operator.cc (hunk 1 above)
Comment (LeoZhao-BJ) [reply paddle/fluid/framework/operator.cc]: I agree, there is case for op running on CPU with a GPU model. But my understanding here  TryCreateTransferScope() is trying to fix GPU memroy explosion, not context cache issue, see comment there:

```
      // In the inference scenerio, the scopes will be reused across the
      // batches, so the `new_scope` here will result in GPU memroy explosion
      // over the  running of operators.
```

Why GPU memroy explosion happens ?  I think it is because data transforming will always ask GPU to allocate memory for output instead of input, there may be some memory management issue on CUDA that memory is not released immediately if we new and delete each time.  Based on this assumption, I think GPU memroy explosion just happens when input is CPU memory while next kernel need GPU memory, so kernel type should be definitely GPU place.

Simply saying, I think TryCreateTransferScope()  is just for solving the issue when input is cpu memory, while next GPU kernel needs gpu memory as input, then TransferScope allocates a GPU memory first for this tranforming.

Anyway, we'd better to sync with original author or chunwei to understand  the scenario of that GPU issue.

**Comment by luotao1** [comment]
```
[02:47:59][Step 3/3] + model_file=model.py
[02:47:59][Step 3/3] + export FLAGS_fraction_of_gpu_memory_to_use=0.0
[02:47:59][Step 3/3] + FLAGS_fraction_of_gpu_memory_to_use=0.0
[02:47:59][Step 3/3] + python model.py
[02:48:00][Step 3/3] grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[02:48:02][Step 3/3] del memory.txt
[02:48:02][Step 3/3] --- Running analysis [ir_graph_build_pass]
[02:48:02][Step 3/3] --- Running analysis [ir_analysis_pass]
[02:48:02][Step 3/3] --- Running IR pass [infer_clean_graph_pass]
[02:48:02][Step 3/3] --- Running IR pass [conv_affine_channel_fuse_pass]
[02:48:02][Step 3/3] --- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
[02:48:02][Step 3/3] --- Running IR pass [conv_bn_fuse_pass]
[02:48:02][Step 3/3] ---  detected 22 subgraphs
[02:48:02][Step 3/3] --- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
[02:48:02][Step 3/3] --- Running IR pass [conv_elementwise_add_act_fuse_pass]
[02:48:02][Step 3/3] ---  detected 22 subgraphs
[02:48:02][Step 3/3] --- Running IR pass [conv_elementwise_add2_act_fuse_pass]
[02:48:02][Step 3/3] --- Running IR pass [conv_elementwise_add_fuse_pass]
[02:48:02][Step 3/3] ---  detected 12 subgraphs
[02:48:02][Step 3/3] --- Running IR pass [transpose_flatten_concat_fuse_pass]
[02:48:02][Step 3/3] --- Running IR pass [runtime_context_cache_pass]
[02:48:02][Step 3/3] --- Running analysis [ir_params_sync_among_devices_pass]
[02:48:02][Step 3/3] I0711 02:48:02.166323  5406 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
[02:48:04][Step 3/3] --- Running analysis [adjust_cudnn_workspace_size_pass]
[02:48:04][Step 3/3] --- Running analysis [inference_op_replace_pass]
[02:48:04][Step 3/3] --- Running analysis [ir_graph_to_program_pass]
[02:48:04][Step 3/3] I0711 02:48:04.235318  5406 analysis_predictor.cc:443] == optimize end ==
[02:48:04][Step 3/3] W0711 02:48:04.482581  5406 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 8.0
[02:48:04][Step 3/3] W0711 02:48:04.485206  5406 device_context.cc:267] device: 0, cuDNN Version: 7.2.
[02:48:05][Step 3/3] ./run.xsh: line 7:  5406 Segmentation fault      python ${model_file}
[02:48:05][Step 3/3] after ./run.xsh
[02:48:05][Step 3/3] befor get_kpi_tasks
[02:48:05][Step 3/3] task_name mobilenet
```
It fails on mobilenet GPU inference. URL see http://ce.paddlepaddle.org:8080/viewLog.html?buildId=52506&tab=buildLog&buildTypeId=Inference_Build&logTab=tree&filter=all&_focus=16279

**Comment by LeoZhao-BJ** [comment]
> ```
> [02:47:59][Step 3/3] + model_file=model.py
> [02:47:59][Step 3/3] + export FLAGS_fraction_of_gpu_memory_to_use=0.0
> [02:47:59][Step 3/3] + FLAGS_fraction_of_gpu_memory_to_use=0.0
> [02:47:59][Step 3/3] + python model.py
> [02:48:00][Step 3/3] grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> [02:48:02][Step 3/3] del memory.txt
> [02:48:02][Step 3/3] --- Running analysis [ir_graph_build_pass]
> [02:48:02][Step 3/3] --- Running analysis [ir_analysis_pass]
> [02:48:02][Step 3/3] --- Running IR pass [infer_clean_graph_pass]
> [02:48:02][Step 3/3] --- Running IR pass [conv_affine_channel_fuse_pass]
> [02:48:02][Step 3/3] --- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
> [02:48:02][Step 3/3] --- Running IR pass [conv_bn_fuse_pass]
> [02:48:02][Step 3/3] ---  detected 22 subgraphs
> [02:48:02][Step 3/3] --- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
> [02:48:02][Step 3/3] --- Running IR pass [conv_elementwise_add_act_fuse_pass]
> [02:48:02][Step 3/3] ---  detected 22 subgraphs
> [02:48:02][Step 3/3] --- Running IR pass [conv_elementwise_add2_act_fuse_pass]
> [02:48:02][Step 3/3] --- Running IR pass [conv_elementwise_add_fuse_pass]
> [02:48:02][Step 3/3] ---  detected 12 subgraphs
> [02:48:02][Step 3/3] --- Running IR pass [transpose_flatten_concat_fuse_pass]
> [02:48:02][Step 3/3] --- Running IR pass [runtime_context_cache_pass]
> [02:48:02][Step 3/3] --- Running analysis [ir_params_sync_among_devices_pass]
> [02:48:02][Step 3/3] I0711 02:48:02.166323  5406 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
> [02:48:04][Step 3/3] --- Running analysis [adjust_cudnn_workspace_size_pass]
> [02:48:04][Step 3/3] --- Running analysis [inference_op_replace_pass]
> [02:48:04][Step 3/3] --- Running analysis [ir_graph_to_program_pass]
> [02:48:04][Step 3/3] I0711 02:48:04.235318  5406 analysis_predictor.cc:443] == optimize end ==
> [02:48:04][Step 3/3] W0711 02:48:04.482581  5406 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 8.0
> [02:48:04][Step 3/3] W0711 02:48:04.485206  5406 device_context.cc:267] device: 0, cuDNN Version: 7.2.
> [02:48:05][Step 3/3] ./run.xsh: line 7:  5406 Segmentation fault      python ${model_file}
> [02:48:05][Step 3/3] after ./run.xsh
> [02:48:05][Step 3/3] befor get_kpi_tasks
> [02:48:05][Step 3/3] task_name mobilenet
> ```
> 
> It fails on mobilenet GPU inference. URL see above.

is it random failure, or always?

**Comment by luotao1** [comment]
It's not random fail.

**Comment by LeoZhao-BJ** [comment]
I searched log, but hard to find useful log,  how can we reproduce locally?
This is segment fault instead of memory leak, so I guess the rootcause may be that TryCreateTransferScope takes effect by "platform::is_gpu_place(kernel_type_for_var.place_)", but we do deletescope by "platform::is_cpu_place(kernel_type_->place_)", this is the case that input is GPU memory while output is cpu memory with cpu kernel, for my assumption, we should not do TryCreateTransferScope() for this case.

I will update code to make a try to let checking condition aligned.

**Comment by luotao1** [comment]
I see it passes the inference CE: http://ce.paddlepaddle.org:8080/viewLog.html?buildId=52541&buildTypeId=Inference_Build&tab=buildResultsDiv

**Comment by luotao1** [comment]
>  this is the case that input is GPU memory while output is cpu memory with cpu kernel, for my assumption, we should not do TryCreateTransferScope() for this case.

Does this assumption cause the memory leak or performance decrease?

File: paddle/fluid/framework/operator.h [hunk 2]
```diff
@@ -502,6 +502,7 @@ class OperatorWithKernel : public OperatorBase {
   mutable bool enable_cache_runtime_context = false;
   mutable bool all_kernels_must_compute_runtime_shape = false;
   mutable std::mutex cache_update_mutex_;
+  mutable bool enable_transferscope_cache = false;
```
Comment (luotao1) [inline paddle/fluid/framework/operator.h]: use_transfer_scope_cache?

File: paddle/fluid/framework/operator.cc [hunk 3]
```diff
@@ -1114,9 +1118,13 @@ Scope* OperatorWithKernel::PrepareData(
       // If this op is not called by an Executor or ParallelExecutor, it should
       // called by a NaiveExecutor, the NaiveExecutor will cache the scopes and
       // variables, that behavior a lot different.
-      if (!run_by_executor_) {
+      enable_transferscope_cache = false;
```
Comment (luotao1) [inline paddle/fluid/framework/operator.cc]: Please add more comments on why only works on `is_gpu_place`, you can paste the issue, and add something like`Have a discussion with @Luotao for cpu inference`

File: paddle/fluid/framework/operator.cc [hunk 4]
```diff
@@ -981,6 +981,10 @@ void OperatorWithKernel::RunImpl(const Scope& scope,
       }
     }
   }
+
+  if (transfer_scope && !run_by_executor_ && !enable_transferscope_cache) {
+    scope.DeleteScope(transfer_scope);
+  }
```
Comment (luotao1) [inline paddle/fluid/framework/operator.cc:990]: Add more comments here.

**Comment by luotao1** [comment]
http://ce.paddlepaddle.org:8080/viewType.html?buildTypeId=Inference_Build&branch_Inference=18578&tab=buildTypeStatusDiv CE inference job passes successfully.

File: paddle/fluid/framework/operator.cc (hunk 4 above)
Comment (LeoZhao-BJ) [reply paddle/fluid/framework/operator.cc:990]: done

File: paddle/fluid/framework/operator.cc (hunk 3 above)
Comment (LeoZhao-BJ) [reply paddle/fluid/framework/operator.cc]: done

File: paddle/fluid/framework/operator.h (hunk 2 above)
Comment (LeoZhao-BJ) [reply paddle/fluid/framework/operator.h]: done

**Review by luotao1 — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
Please review this fix! @Superjomn

File: paddle/fluid/framework/operator.h [hunk 5]
```diff
@@ -502,6 +502,7 @@ class OperatorWithKernel : public OperatorBase {
   mutable bool enable_cache_runtime_context = false;
   mutable bool all_kernels_must_compute_runtime_shape = false;
   mutable std::mutex cache_update_mutex_;
+  mutable bool enable_cache_transfer_scope = false;
```
Comment (Superjomn) [inline paddle/fluid/framework/operator.h]: 这几个 member貌似都不符合规范，member 需要加 `_` 后缀

Comment (luotao1) [reply paddle/fluid/framework/operator.h]: OK，I will help change it.

Comment (luotao1) [reply paddle/fluid/framework/operator.h]: Done

**Review by Superjomn — APPROVED** [review]
LGTM

**Review by luotao1 — APPROVED** [review]
