### PR TITLE
Fix a bug for TransLayer and add unit testing.

### LINKED ISSUE #1805: Bug for translayer ?
Under paddle/gserver/layers/TransLayer.cpp

For back propagation the gradient is directly assigned:

`  MatrixPtr preGrad = getInputGrad(0); `
 ` outputGrad->transpose(preGrad, false);`

Will there be a problem when you have this layer connect to multiple branches?  During the backward process, the gradient will be overwritten by the last branch, while missing the gradient from others.

Thanks.

### PR DESCRIPTION
**Pull request by qingqing01**
Fix #1805

### CODE REVIEW

File: paddle/gserver/layers/TransLayer.cpp [hunk 1]
```diff
@@ -56,7 +56,14 @@ void TransLayer::backward(const UpdateCallback& callback) {
     return;
   }
   MatrixPtr preGrad = getInputGrad(0);
-  outputGrad->transpose(preGrad, false);
+  if (preGrad) {
+    MatrixPtr transGrad = Matrix::create(preGrad->getHeight(),
```
Comment (pengwangucla) [inline paddle/gserver/layers/TransLayer.cpp]: Does not need to create a memory outside, you may use transpose(transGrad, true) to allocate the memory inside
