### PR TITLE
Fix several bugs in compile time backward and Protobuf desc

### LINKED ISSUE #4893: Several bugs in compile time backward and Protobuf desc
There are several bugs in our compile time backward and Protobuf desc(ProgramDesc, BlockDesc ...):

1. `BlockDescBind::AllOps()` is a C++ interface exposed to Python. It returns a `std::vector` which contains pointers of all `OpDescBind`. However, it seems that even if we have set the transmit mode as `reference`, Python will still get the ownership of the `std::vector` and destroy it after using. That means, once we call `BlockDescBind::AllOps()` in Python, all `OpDescBind` holded by this block will be destroyed. 

2. We use a label `need_update_` to mark whether a `BlockDescBind` or `OpDescBind` object needs to be flushed. When `BlockDescBind::Flush()` is invoked, we shall check both `BlockDescBind::need_update_` and `OpDescBind::need_update_` to decide whether we need to do a real flush(Because some changes in `OpDescBind` may not influence the `need_update_` in `BlockDescBind`). However, in the current code, we only check `BlockDescBind::need_update_`.

3. For the convenience of appending backwards, we temporarily set data members of `BlockDescBind` as `public`. It leads to that data members can be mutated without setting `need_update_` true.

### PR DESCRIPTION
**Pull request by Canpio**
fixes #4893 

This PR is branched from https://github.com/PaddlePaddle/Paddle/pull/4868, so some changed may belong to that one and have no relationship with this topic.

### CODE REVIEW

File: paddle/framework/block_desc.cc [hunk 1]
```diff
@@ -55,6 +55,12 @@ OpDescBind *BlockDescBind::AppendOp() {
   return ops_.back().get();
 }
 
+void BlockDescBind::AppendAllocatedOp(std::unique_ptr<OpDescBind> &op_desc) {
```
Comment (reyoung) [inline paddle/framework/block_desc.cc]: I think it is pretty hard to figure out the `op_desc` has been changed inside `AppendAllocatedOp` for others.

It is better to use `std::move` outside, and accept the `rvalue reference` here.

File: paddle/framework/block_desc.cc [hunk 2]
```diff
@@ -55,6 +55,12 @@ OpDescBind *BlockDescBind::AppendOp() {
...
+  need_update_ = true;
+  ops_.emplace_back(std::move(op_desc));
+  return;
```
Comment (reyoung) [inline paddle/framework/block_desc.cc]: `return` is not needed.

File: paddle/framework/block_desc.h [hunk 3]
```diff
@@ -57,10 +57,16 @@ class BlockDescBind {
...
 
+  void AppendAllocatedOp(std::unique_ptr<OpDescBind> &op_desc);
+
   OpDescBind *PrependOp();
 
   std::vector<OpDescBind *> AllOps() const;
 
+  int OpSize() const { return ops_.size(); }
+
+  OpDescBind *Op(int idx) const { return ops_.at(idx).get(); }
```
Comment (reyoung) [inline paddle/framework/block_desc.h]: use size_t as idx, also maybe do not mark this method as `const` since it will change the program.

File: paddle/pybind/protobuf.cc [hunk 4]
```diff
@@ -176,8 +176,10 @@ void BindBlockDesc(py::module &m) {
            py::return_value_policy::reference)
       .def("all_vars", &BlockDescBind::AllVars,
            py::return_value_policy::reference)
-      .def("all_ops", &BlockDescBind::AllOps,
-           py::return_value_policy::reference)
+      // .def("all_ops", &BlockDescBind::AllOps,
```
Comment (reyoung) [inline paddle/pybind/protobuf.cc]: remove it

File: paddle/framework/block_desc.cc (hunk 1 above)
Comment (Canpio) [reply paddle/framework/block_desc.cc]: Good idea!

File: paddle/framework/block_desc.cc (hunk 2 above)
Comment (Canpio) [reply paddle/framework/block_desc.cc]: Done.

File: paddle/framework/block_desc.h [hunk 5]
```diff
@@ -57,10 +57,16 @@ class BlockDescBind {
 
   OpDescBind *AppendOp();
 
+  void AppendAllocatedOp(std::unique_ptr<OpDescBind> &op_desc);
+
   OpDescBind *PrependOp();
 
   std::vector<OpDescBind *> AllOps() const;
 
+  int OpSize() const { return ops_.size(); }
```
[the remark this answers is not in the document]
Comment (Canpio) [reply paddle/framework/block_desc.h]: Done

File: paddle/framework/block_desc.h (hunk 3 above)
Comment (Canpio) [reply paddle/framework/block_desc.h]: Done

File: paddle/pybind/protobuf.cc (hunk 4 above)
Comment (Canpio) [reply paddle/pybind/protobuf.cc]: Done.
