### PR TITLE
fix error cmake infomation

### LINKED ISSUE #2113: The error information of cudnn is wrong
when running gpu demo, if users don't have the correct cudnn pass:
```
I0512 16:12:11.301077 22465 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
F0512 16:12:11.792135 22465 DynamicLoader.cpp:104] Check failed: nullptr != *dso_handle Failed to find dynamic library: libcudnn.so (libcudnn.so: cannot open shared object file: No such file or directory) 
Please specify its path correctly using one of the following ways: 
Method 1. set cuda and cudnn lib path at runtime. http://www.paddlepaddle.org/doc/ui/cmd_argument/argument_outline.html 
For instance, issue command: paddle train --use_gpu=1 --cuda_dir=/usr/local/cuda/lib64 --cudnn_dir=/usr/local/cudnn/lib ...
Method 2. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
For instance, issue command: export LD_LIBRARY_PATH=... 
```
The url in Method 1 can not open now.

### PR DESCRIPTION
**Pull request by luotao1**
fix #2113

### CODE REVIEW

File: paddle/utils/DynamicLoader.cpp [hunk 1]
```diff
@@ -104,20 +104,9 @@ static inline void GetDsoHandleFromSearchPath(const std::string& search_root,
...
-                                   "argument_outline.html \n"
-                                << "For instance, issue command: paddle train "
-                                   "--use_gpu=1 "
-                                << "--cuda_dir=/usr/local/cuda/lib64 "
-                                   "--cudnn_dir=/usr/local/cudnn/lib "
-                                   "...\n"
-
-                                << "Method 2. set environment variable "
+                                   "following ways: \n"
+
```
Comment (gangliao) [inline paddle/utils/DynamicLoader.cpp]: ~~However, method 1 always works well.~~

Comment (luotao1) [inline paddle/utils/DynamicLoader.cpp]: Done
