### PR TITLE
Fix dist transpiler develop

### LINKED ISSUE #8393: split_op error on Alloc()
The program was:

```
  ops {
    inputs {
      parameter: "X"
      arguments: "conv2d_1.w_0@GRAD"
    }
    outputs {
      parameter: "Out"
      arguments: "conv2d_1.w_0@GRAD.block0"
      arguments: "conv2d_1.w_0@GRAD.block1"
      arguments: "conv2d_1.w_0@GRAD.block2"
      arguments: "conv2d_1.w_0@GRAD.block3"
      arguments: "conv2d_1.w_0@GRAD.block4"
      arguments: "conv2d_1.w_0@GRAD.block5"
      arguments: "conv2d_1.w_0@GRAD.block6"
      arguments: "conv2d_1.w_0@GRAD.block7"
      arguments: "conv2d_1.w_0@GRAD.block8"
      arguments: "conv2d_1.w_0@GRAD.block9"
    }
    type: "split"
    attrs {
      name: "axis"
      type: INT
      i: 0
    }
    attrs {
      name: "num"
      type: INT
      i: 0
    }
    attrs {
      name: "sections"
      type: INTS
      ints: 5
      ints: 5
      ints: 5
      ints: 5
      ints: 5
      ints: 5
      ints: 5
      ints: 5
      ints: 5
      ints: 5
    }
  }
```

Execute the op returns: 

```
*** Aborted at 1518357089 (unix time) try "date -d @1518357089" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 6009 (TID 0x7f4802281700) from PID 0; stack trace: ***
    @     0x7f48018557e0 (unknown)
    @     0x7f47c8539d58 paddle::memory::detail::MetadataCache::load()
    @     0x7f47c853a6dc paddle::memory::detail::MemoryBlock::split()
    @     0x7f47c85389d2 _ZN6paddle6memory6detail14BuddyAllocator12SplitToAllocESt23_Rb_tree_const_iteratorISt5tupleIJmmPvEEEm
    @     0x7f47c8538eb4 paddle::memory::detail::BuddyAllocator::Alloc()
    @     0x7f47c8535be1 paddle::memory::Alloc<>()
    @     0x7f47c8496fa4 paddle::framework::Tensor::PlaceholderImpl<>::PlaceholderImpl()
    @     0x7f47c84973c7 paddle::framework::Tensor::mutable_data()
    @     0x7f47c893a611 paddle::operators::SplitOpKernel<>::Compute()
    @     0x7f47c8ed4788 paddle::framework::OperatorWithKernel::Run()
    @     0x7f47c853bc7d paddle::framework::Executor::Run()
    @     0x7f47c84a8a61 _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEJRKNS4_11ProgramDescEPNS4_5ScopeEibbEJNS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vJSO_S8_SA_ibbEJSB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_
    @     0x7f47c84a2be2 pybind11::cpp_function::dispatcher()
    @     0x7f4801b6ece8 PyEval_EvalFrameEx
    @     0x7f4801b7137d PyEval_EvalCodeEx
    @     0x7f4801b6ed70 PyEval_EvalFrameEx
    @     0x7f4801b7137d PyEval_EvalCodeEx
    @     0x7f4801b714b2 PyEval_EvalCode
    @     0x7f4801b9b1c2 PyRun_FileExFlags
    @     0x7f4801b9c559 PyRun_SimpleFileExFlags
    @     0x7f4801bb21dd Py_Main
    @     0x7f4800e45d1d __libc_start_main
    @           0x4006b1 (unknown)
```

### PR DESCRIPTION
**Pull request by typhoonzero**
Fix dist train in develop branch after merge https://github.com/PaddlePaddle/Paddle/pull/8209

Fixed #8393

### CODE REVIEW

File: paddle/fluid/operators/strided_memcpy.h [hunk 1]
```diff
@@ -58,6 +58,7 @@ inline void StridedNumelCopyWithAxis(const platform::DeviceContext& ctx,
   int64_t before = dst_stride_numel[0] / dst_stride_numel[axis];
   int64_t src_after = src_stride_numel[axis];
   int64_t dst_after = dst_stride_numel[axis];
+  int64_t copy_size = std::min(src_after, dst_after);
```
Comment (Yancey1989) [inline paddle/fluid/operators/strided_memcpy.h]: As the offline discuss, `min` is confusion, maybe pass the `copy_size` as a parameter is a better way.
