### PR TITLE
fix dist train error

### LINKED ISSUE #11268: fluid_benchmark.sh crash
image

```
*** Aborted at 1528352945 (unix time) try "date -d @1528352945" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 84785 (TID 0x7f44c83e9700) from PID 0; stack trace: ***
    @     0x7f44c7bbc7e0 (unknown)
    @     0x7f4470497610 paddle::platform::is_gpu_place()
    @     0x7f447031fb6e paddle::framework::OperatorBase::Run()
    @     0x7f447018455a paddle::framework::details::RPCOpHandle::RunImpl()
    @     0x7f44701a6677 paddle::framework::details::OpHandleBase::Run()
    @     0x7f447019d5aa _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS0_13BlockingQueueIPNS1_13VarHandleBaseEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7f447019df62 paddle::framework::details::ThreadedSSAGraphExecutor::RunOp()
    @     0x7f447019f3ae paddle::framework::details::ThreadedSSAGraphExecutor::Run()
    @     0x7f44701a4685 paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
    @     0x7f446f680dad paddle::framework::ParallelExecutor::Run()
    @     0x7f446f605c16 _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework16ParallelExecutorEIRKSt6vectorISsSaISsEERKSsEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_SA_SC_E_vISQ_SA_SC_EISD_SE_SF_EEEvOSH_PFSG_SJ_ESP_ENUlRNS_6detail13function_callEE1_4_FUNESX_
    @     0x7f446f5ddf74 pybind11::cpp_function::dispatcher()
    @     0x7f44c7ed5ce8 PyEval_EvalFrameEx
    @     0x7f44c7ed837d PyEval_EvalCodeEx
    @     0x7f44c7ed5d70 PyEval_EvalFrameEx
    @     0x7f44c7ed837d PyEval_EvalCodeEx
    @     0x7f44c7e4f830 (unknown)
    @     0x7f44c7e1dd33 PyObject_Call
    @     0x7f44c7ed30a2 PyEval_EvalFrameEx
    @     0x7f44c7ed5e9e PyEval_EvalFrameEx
    @     0x7f44c7ed837d PyEval_EvalCodeEx
    @     0x7f44c7ed84b2 PyEval_EvalCode
    @     0x7f44c7f021c2 PyRun_FileExFlags
    @     0x7f44c7f03559 PyRun_SimpleFileExFlags
    @     0x7f44c7f191dd Py_Main
    @     0x7f44c71acd1d __libc_start_main
    @           0x4006b1 (unknown)
*** Aborted at 1528352945 (unix time) try "date -d @1528352945" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 84784 (TID 0x7f5604276700) from PID 0; stack trace: ***
    @     0x7f5603a497e0 (unknown)
    @     0x7f55ac2a4610 paddle::platform::is_gpu_place()
    @     0x7f55ac12cb6e paddle::framework::OperatorBase::Run()
    @     0x7f55abf9155a paddle::framework::details::RPCOpHandle::RunImpl()
    @     0x7f55abfb3677 paddle::framework::details::OpHandleBase::Run()
    @     0x7f55abfaa5aa _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS0_13BlockingQueueIPNS1_13VarHandleBaseEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7f55abfaaf62 paddle::framework::details::ThreadedSSAGraphExecutor::RunOp()
    @     0x7f55abfac3ae paddle::framework::details::ThreadedSSAGraphExecutor::Run()
    @     0x7f55abfb1685 paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run()
    @     0x7f55ab48ddad paddle::framework::ParallelExecutor::Run()
```

### PR DESCRIPTION
**Pull request by Yancey1989**
Fixed #11268

### CODE REVIEW

File: paddle/fluid/framework/details/rpc_op_handle.h [hunk 1]
```diff
@@ -29,7 +29,7 @@ namespace details {
 
 struct RPCOpHandle : public OpHandleBase {
   RPCOpHandle(const framework::OpDesc& op_desc, const Scope* local_scope,
-              const platform::Place& place, const std::string& name);
+              const std::string& name, platform::Place place);
```
Comment (panyx0718) [inline paddle/fluid/framework/details/rpc_op_handle.h]: you can keep this as const ref
