### PR TITLE
Fix bug in MultiGradientMachine.

### LINKED ISSUE #2649: Bug in paddle::TrainerThread::gradCollectThread().
If the batch size in one mini-batch is smaller than the `trainer_count` and there is static parameter in the network, the code will crash. The error is as follows:

```
*** Aborted at 1498592614 (unix time) try "date -d @1498592614" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGSEGV (@0x29) received by PID 12513 (TID 0x7f8ec692b700) from PID 41; stack trace: ***

    @       0x318b20f500 (unknown)

    @     0x7f8eea1ee173 paddle::BaseMatrixT<>::add()

    @     0x7f8eea1311be paddle::TrainerThread::gradCollectThread()

    @     0x7f8ee98002d0 execute_native_thread_routine

    @       0x318b207851 (unknown)

    @       0x318aee767d (unknown)

    @                0x0 (unknown)
```

### PR DESCRIPTION
**Pull request by qingqing01**
Fix #2649

### CODE REVIEW

File: paddle/gserver/gradientmachines/MultiGradientMachine.cpp [hunk 1]
```diff
@@ -601,7 +601,7 @@ void TrainerThread::backward() {
 
 void TrainerThread::backwardCallback(Parameter* para) {
   // CPU parameters are merged in the end
-  if (!para->useGpu()) return;
+  if (!para->useGpu() || para->isStatic()) return;
```
Comment (pkuyym) [inline paddle/gserver/gradientmachines/MultiGradientMachine.cpp]: Better to add detail comments here.

Comment (qingqing01) [inline paddle/gserver/gradientmachines/MultiGradientMachine.cpp]: If the batch size for one thread is 0, all the parameters will call `backwardCallback ` function to merge gradient in the line [593](https://github.com/PaddlePaddle/Paddle/pull/2650/files#diff-13b947557637acb90d7b810c647bf277R593). But the static parameters which do not need to be updated should not call `backwardCallback `. So add a check here.
