### PR TITLE
Fix NCCLBcast hang up bug in Parallel Executor

### LINKED ISSUE #11375: 当ParallelExecutor运行在已被占用的GPU上时, Trainer夯住
复现过程如下:

环境: GPU 0-3 空闲, 4-7被占用
Tesla P40, 0 MiB
Tesla P40, 0 MiB
Tesla P40, 0 MiB
Tesla P40, 0 MiB
Tesla P40, 20391 MiB
Tesla P40, 20391 MiB
Tesla P40, 20391 MiB
Tesla P40, 20391 MiB

1. 将Pserver启动在0,1两个GPU上:

```bash
CUDA_VISIBLE_DEVICES=0,1 PADDLE_TRAINING_ROLE=PSERVER PADDLE_PSERVER_PORT=7164 PADDLE_PSERVER_IPS=127.0.0.1 PADDLE_TRAINERS=1 PADDLE_CURRENT_IP=127.0.0
.1 PADDLE_TRAINER_ID=0 python fluid/fluid_benchmark.py --gpus 2 --device GPU --model resnet --update_method pserver &   
sleep 5
```

2. 将 Trainer 启动在 3,4 两号 GPU 上, 此时 3 号 GPU 空闲, 4 号 GPU 被占用:

``` bash
CUDA_VISIBLE_DEVICES=3,4 GLOG_logtostderr=1 GLOG_v=4 PADDLE_TRAINING_ROLE=TRAINER PADDLE_PSERVER_PORT=7164 PADDLE_PSERVER_IPS=127.0.0.1 PADDLE_TRAINERS=1 PADDLE_CURRENT_IP=127.0.0.1 PADDLE_TRAINER_ID=0 python fluid/fluid_benchmark.py --gpus 2 --device GPU --model resnet --update_method pserver
```

结果: Trainer长时间被夯住

### PR DESCRIPTION
**Pull request by velconia**
this close #11375

### CODE REVIEW

File: paddle/fluid/framework/parallel_executor.cc [hunk 1]
```diff
@@ -63,7 +64,17 @@ ParallelExecutor::ParallelExecutor(
   member_->global_scope_ = scope;
   member_->use_cuda_ = exec_strategy.use_cuda_;
 
-  // Step 1. Bcast the params to devs.
+  // Step 1. check all memory usages of all places.
```
Comment (jacquesqiao) [inline paddle/fluid/framework/parallel_executor.cc]: So these code is not needed?

Comment (velconia) [reply paddle/fluid/framework/parallel_executor.cc]: I think these messages should be print out also, so I didn't remove it.

File: paddle/fluid/platform/nccl_helper.h [hunk 2]
```diff
@@ -41,6 +41,11 @@ inline ncclDataType_t ToNCCLDataType(std::type_index type) {
   }
 }
 
+// NOTE(minqiyang): according to the ncclGroupEnd documentations:
```
Comment (typhoonzero) [inline paddle/fluid/platform/nccl_helper.h]: Well, I think we can assume people who develop paddlepaddle with this file is familiar with the NCCL natives.

File: paddle/fluid/framework/parallel_executor.cc [hunk 3]
```diff
@@ -159,11 +170,21 @@ void ParallelExecutor::BCastParamsToGPUs(
...
+      PADDLE_ENFORCE_EQ(member_->places_.size(), buffers.size(),
+                        "variables' buffer size to bcast NOT equal to places");
+      {
+        platform::NCCLGroupGuard guard;
+        for (size_t i = 0; i < member_->places_.size(); ++i) {
+          auto &nccl_ctx = member_->nccl_ctxs_->at(member_->places_[i]);
+          platform::dynload::ncclBcast(buffers[i], numel, data_type, 0,
+                                       nccl_ctx.comm_, nccl_ctx.stream());
+        }
+        member_->nccl_ctxs_->WaitAll();
```
Comment (typhoonzero) [inline paddle/fluid/framework/parallel_executor.cc]: This line may not needed? since `ncclgroupend` will sync all group calls.

File: paddle/fluid/framework/parallel_executor.cc [hunk 4]
```diff
@@ -63,7 +64,17 @@ ParallelExecutor::ParallelExecutor(
   member_->global_scope_ = scope;
   member_->use_cuda_ = exec_strategy.use_cuda_;
 
-  // Step 1. Bcast the params to devs.
+  // Step 1. check all memory usages of all places.
+  // This step will create BuddyAllocator for each place, which will
+  //    1. enforce that the place is avaliable and NOT used.
+  //    2. avoid ncclBcast hanging up for NOT enough memory to use.
+  for (size_t i = 0; i < member_->places_.size(); ++i) {
```
Comment (typhoonzero) [inline paddle/fluid/framework/parallel_executor.cc]: Does these lines was intended to let the process fail fast?

File: paddle/fluid/platform/nccl_helper.h (hunk 2 above)
Comment (velconia) [reply paddle/fluid/platform/nccl_helper.h]: To avoid this bug happens again, I leave these comments.

File: paddle/fluid/framework/parallel_executor.cc (hunk 4 above)
Comment (velconia) [reply paddle/fluid/framework/parallel_executor.cc]: yes

File: paddle/fluid/framework/parallel_executor.cc (hunk 3 above)
Comment (typhoonzero) [reply paddle/fluid/framework/parallel_executor.cc]: @chengduoZH Can you please help take a look at this?

Comment (chengduoZH) [reply paddle/fluid/framework/parallel_executor.cc]: @typhoonzero line 185 is necessary,
- `ncclgroupend` only ensures that there is only one thread can invoke nccl function, but not sync the calls.
- the invoking of nccl functions is async, so we need use `WaitAll()` to ensure the invoking have completed on GPU side.

File: paddle/fluid/framework/parallel_executor.cc [hunk 5]
```diff
@@ -145,9 +156,9 @@ void ParallelExecutor::BCastParamsToGPUs(
     auto &dims = main_tensor.dims();
     if (paddle::platform::is_gpu_place(main_tensor.place())) {
 #ifdef PADDLE_WITH_CUDA
```
Comment (chengduoZH) [inline paddle/fluid/framework/parallel_executor.cc]: I don't think the modify of line159~167 is necessary.
Because if the memory of one Place is insufficient, the program will throw an exception in this [line](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/gpu_info.cc#L119).

Comment (velconia) [reply paddle/fluid/framework/parallel_executor.cc]: Actually, the thrown exception will not be handled properly, this PR was submitted to fix this [bug](https://github.com/PaddlePaddle/Paddle/issues/11375)

File: paddle/fluid/framework/parallel_executor.cc [hunk 6]
```diff
@@ -63,7 +64,17 @@ ParallelExecutor::ParallelExecutor(
...
-  // Step 1. Bcast the params to devs.
+  // Step 1. check all memory usages of all places.
+  // This step will create BuddyAllocator for each place, which will
+  //    1. enforce that the place is avaliable and NOT used.
+  //    2. avoid ncclBcast hanging up for NOT enough memory to use.
+  for (size_t i = 0; i < member_->places_.size(); ++i) {
+    size_t usage = memory::memory_usage(member_->places_[i]);
+    VLOG(4) << "Memory usage of device: " << member_->places_[i] << " is "
+            << usage << " bytes";
+  }
```
Comment (chengduoZH) [inline paddle/fluid/framework/parallel_executor.cc]: This check just should do one time. So maybe it is not appropriate for placing it here.

Comment (velconia) [reply paddle/fluid/framework/parallel_executor.cc]: Because BuddyAllocator's array was a static member in function in this [line](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/memory/malloc.cc#L62), so this check can do many times in the constructor in  ParallelExecutor

File: paddle/fluid/framework/parallel_executor.cc [hunk 7]
```diff
@@ -25,6 +25,7 @@ limitations under the License. */
 #include "paddle/fluid/framework/details/scope_buffered_ssa_graph_executor.h"
 #include "paddle/fluid/framework/details/ssa_graph_builder_factory.h"
 #include "paddle/fluid/framework/details/threaded_ssa_graph_executor.h"
+#include "paddle/fluid/memory/malloc.h"
```
Comment (chengduoZH) [inline paddle/fluid/framework/parallel_executor.cc]: Remove this line.

File: paddle/fluid/framework/parallel_executor.cc [hunk 8]
```diff
@@ -63,7 +64,7 @@ ParallelExecutor::ParallelExecutor(
   member_->global_scope_ = scope;
   member_->use_cuda_ = exec_strategy.use_cuda_;
 
-  // Step 1. Bcast the params to devs.
+  // Step 2. Bcast the params to devs.
```
Comment (chengduoZH) [inline paddle/fluid/framework/parallel_executor.cc]: ==> Step 1.
