### PR TITLE
Optimize the content of error reporting information, print error code and official document web sites

### LINKED ISSUE #18668: 优化报错信息内容，增加安装流程的体验度
报错信息建议为：
cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability!
Error Type ID = 1, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

### PR DESCRIPTION
**Pull request by zhwesky2010**
resolve #18668
错误信息修改为：举例：cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability!
error code = 1, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

### CODE REVIEW

File: paddle/fluid/platform/gpu_info.cc [hunk 1]
```diff
@@ -92,9 +98,12 @@ static int GetCUDADeviceCountImpl() {
...
 
   int count;
+  auto error_code = cudaGetDeviceCount(&count);
   PADDLE_ENFORCE(
-      cudaGetDeviceCount(&count),
-      "cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount");
+      error_code,
+      "cudaGetDeviceCount failed in "
+      "paddle::platform::GetCUDADeviceCountImpl, error code : %d, %s",
+      error_code, CudaErrorWebsite());
```
Comment (liupluswei) [inline paddle/fluid/platform/gpu_info.cc:106]: please figure out whether you can use string with %s here

**Review by liupluswei — APPROVED** [review]
LGTM

File: paddle/fluid/platform/gpu_info.cc (hunk 1 above)
Comment (zhwesky2010) [reply paddle/fluid/platform/gpu_info.cc:106]: Yes, Sprintf() can support string with %s in experiment.
