### PR TITLE
Fix unittests

### LINKED ISSUE #10242: Remove default argument of TensorCopy
https://github.com/PaddlePaddle/Paddle/pull/10232#pullrequestreview-115658651

### PR DESCRIPTION
**Pull request by JiayiFeng**
Fix several unit tests by modifying their `TensorCopy` invocation from asynchronous to synchronous.

And fix #10242

### CODE REVIEW

**Comment by JiayiFeng** [comment]
@wangkuiyi Done. Thanks!

File: paddle/fluid/framework/tensor_util.h [hunk 1]
```diff
@@ -24,10 +24,11 @@ namespace paddle {
 namespace framework {
 
 void TensorCopy(const Tensor& src, const platform::Place& dst_place,
```
Comment (chengduoZH) [inline paddle/fluid/framework/tensor_util.h]: Now that we have `TensorCopySync`, I think we should have `TensorCopyAsync` correspondingly, it should be explicit.

Comment (JiayiFeng) [reply paddle/fluid/framework/tensor_util.h]: I agree. The `TensorCopy` should be `TensorCopyAsync`. However, this modification might be a heavy job for `TensorCopy` is widely used in our current code. Maybe it's better to leave it to further PRs.
