### PR TITLE
Fix seq concat op with refactoring LoD 

### LINKED ISSUE #5039: The seq_concat_op should correctly process LoD since the meaning of LoD has been changed.
The [issue#4945](https://github.com/PaddlePaddle/Paddle/issues/4945) change LoD's absolute offsets to relative offsets, especially for the more than 1 level sequence. So the `seq_concat_op`  should correctly process LoD and update the unit testing: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/tests/test_seq_concat_op.py#L11

### PR DESCRIPTION
**Pull request by Yancey1989**
Fixed #5039

### CODE REVIEW

File: paddle/operators/sequence_concat_op.h [hunk 1]
```diff
@@ -24,28 +24,38 @@ using LoDTensor = framework::LoDTensor;
 using LoD = framework::LoD;
 
 template <typename T>
-LoD concatLoD(const std::vector<const T*> ins, const size_t axis,
-              const size_t level) {
+LoD concatLoD(const std::vector<const T*> ins, const size_t level) {
```
Comment (qingqing01) [inline paddle/operators/sequence_concat_op.h]: concatLoD -> ConcatLoD
