### PR TITLE
Fix abort issue in cpu multi-threads

### LINKED ISSUE #11231: abort in multi-threads infer on CPU
This is an issue started here https://github.com/PaddlePaddle/Paddle/issues/11185#issuecomment-394605215. @ChinaLiuhao

It would randomly aborted when use multi-threads.

### PR DESCRIPTION
**Pull request by tensor-tang**
fix #11231 

The key backtrace is :
```txt
#16 0x00000000029b4640 in paddle::framework::Scope::Var (this=0x5cfd0e0, name="lstm_0.w_0")
    at /home/tangjian/paddle-docker/paddle/fluid/framework/scope.cc:55
#17 0x0000000002705d91 in paddle::framework::Executor::CreateVariables (this=0x7f07caffcab0, pdesc=...,
    scope=0x7f07b8022850, block_id=0) at /home/tangjian/paddle-docker/paddle/fluid/framework/executor.cc:94
#18 0x0000000002709942 in paddle::framework::Executor::RunPreparedContext (this=0x7f07caffcab0, ctx=0x7f07b8022990,
    scope=0x5cfd0e0, create_local_scope=true, create_vars=true)
    at /home/tangjian/paddle-docker/paddle/fluid/framework/executor.cc:316
#19 0x0000000002706597 in paddle::framework::Executor::Run (this=0x7f07caffcab0, pdesc=..., scope=0x5cfd0e0,
    block_id=0, create_local_scope=true, create_vars=true)
    at /home/tangjian/paddle-docker/paddle/fluid/framework/executor.cc:119
#20 0x00000000022e875e in paddle::inference::LoadPersistables (executor=0x7f07caffcab0, scope=0x5cfd0e0,
    main_program=..., dirname="/home/tangjian/nlp/epoch6", param_filename="")
    at /home/tangjian/paddle-docker/paddle/fluid/inference/io.cc:108
#21 0x00000000022e8c34 in paddle::inference::Load (executor=0x7f07caffcab0, scope=0x5cfd0e0,
    dirname="/home/tangjian/nlp/epoch6") at /home/tangjian/paddle-docker/paddle/fluid/inference/io.cc:124
#22 0x0000000002244eed in ThreadRunInfer (tid=5, scope=0x5cfd0e0, jobs=std::vector of length 6, capacity 6 = {...})
    at /home/tangjian/paddle-docker/paddle/fluid/inference/tests/book/test_inference_nlp.cc:111
```

### CODE REVIEW

**Comment by tensor-tang** [comment]
https://paddleci.ngrok.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=38034&_focus=5958

> [Step 1/1] 305/334 Test #295: test_listen_and_serv_op .........................***Timeout  31.59 sec

File: paddle/fluid/inference/tests/book/test_inference_nlp.cc [hunk 1]
```diff
@@ -101,23 +101,22 @@ void SplitData(
...
-    const int tid, paddle::framework::Executor* executor,
-    paddle::framework::Scope* scope,
-    const std::unique_ptr<paddle::framework::ProgramDesc>& inference_program,
+    const int tid, paddle::framework::Scope* scope,
     const std::vector<std::vector<const paddle::framework::LoDTensor*>>& jobs) {
-  auto copy_program = std::unique_ptr<paddle::framework::ProgramDesc>(
-      new paddle::framework::ProgramDesc(*inference_program));
+  // maybe framework:ProgramDesc is not thread-safe
   auto& sub_scope = scope->NewScope();
+  auto place = paddle::platform::CPUPlace();
```
Comment (panyx0718) [inline paddle/fluid/inference/tests/book/test_inference_nlp.cc]: paddle::platform::CPUPlace place;
paddle::framework::Executor executor(place);

File: paddle/fluid/inference/tests/book/test_inference_nlp.cc [hunk 2]
```diff
@@ -189,21 +175,30 @@ TEST(inference, nlp) {
...
     for (int i = 0; i < FLAGS_num_threads; ++i) {
       threads[i]->join();
     }
     stop_ms = GetCurrentMs();
   } else {
-    if (FLAGS_prepare_vars) {
-      executor.CreateVariables(*inference_program, scope.get(), 0);
+    // 1. Define place, executor, scope
+    auto place = paddle::platform::CPUPlace();
+    auto executor = paddle::framework::Executor(place);
```
Comment (panyx0718) [inline paddle/fluid/inference/tests/book/test_inference_nlp.cc]: same as above
